#!/usr/bin/env node
/**
 * Remove the build artefact directories so the next `npm run build`
 * produces a fresh tree. Targets:
 *   - `.deploy/`  Round 20 deploy artefact (mirrored to gh-pages)
 *   - `dist/`     legacy bundle dir (gitignored; only locally-built
 *                 placeholders remain, regenerated by `build:css` /
 *                 `build:js` on demand)
 *
 * Anchored to `findRepoRoot()` so invoking from any subdirectory
 * removes the right tree (and never escapes the repo).
 */

import { rmSync } from 'node:fs';
import path from 'node:path';

import { findRepoRoot } from './lib/repo-root.js';

const ROOT = findRepoRoot();

for (const dir of ['.deploy', 'dist']) {
  rmSync(path.join(ROOT, dir), { recursive: true, force: true });
}
